name: qr_create
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  screenshot: ^3.0.0
  hive: ^2.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/image/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700

flutter_launcher_icons:  
  android: true
  ios: true
  image_path: "assets/image/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#800080" # Purple background
  image: assets/image/splash_screen.png
  android: true
  ios: true
  fullscreen: true
